resolve-type-alias: False # https://vektra.github.io/mockery/v2.51/deprecations/#resolve-type-alias
issue-845-fix: True # https://vektra.github.io/mockery/v2.51/deprecations/#issue-845-fix
with-expecter: true
inpackage: false
packages:
  github.com/KennyMacCormik/HerdMaster/pkg/cache:
    interfaces:
      Interface:
        config:
          dir: "cache/mocks"